### ISSUE TITLE
ссылки на ресурсы в коде

### ISSUE THREAD

**Issue by mprohorovevapps** [plutosshow/praktic2020#7]
Все ссылки на ресурсы, такие как:
```html
<link rel="stylesheet" href="vendor/twbs/bootstrap/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="css/style.css">
```
должны быть абсолютными (ресурсы подключаются от корня сайта)
```html
<link rel="stylesheet" href="/vendor/twbs/bootstrap/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="/css/style.css">
<img src="/img/svg/Vector.svg" alt="">
```
Иначе при переходах на внутренние страницы, стили, скрипты, изображения будт не доступны.

**Comment by mprohorovevapps** [comment]
Не, не. Так
```html
<link rel="stylesheet" href="./css/style.css">
<!--обрати внимание на точку-->
```
не правильно.
Если пользователь будет находится, например, на странице hungry-people.ru/about/, то при таком задании пути к файлу браузер будет искать путь **hungry-people.ru/about/css/style.css**  и вернёт 404 ошибку. А вот, если задать путь:
```html
<link rel="stylesheet" href="/css/style.css">
<!--обрати внимание на точку-->
```
то файл будет искаться по пути hungry-people.ru/css/style.css, не зависимо от того, на какой странице находится пользователь.

**Comment by plutosshow** [comment]
`<link rel="stylesheet" href="/css/style.css">`
Когда я делаю так у меня перестают работать стили

**Comment by mprohorovevapps** [comment]
А ты просто в файлах верстаешь или есть какая нибудь среда? У тебя операционка windows я так понимаю?

**Comment by plutosshow** [comment]
Windows в Visual Studio Code

**Comment by mprohorovevapps** [comment]
https://ospanel.io/download/
Вот такую штуку установи себе и под ним делай. Он тебе сервер с php, mysql  и другими плюшками поднимет и ссылки будут правильно работать. И на машину не нужно будет ничего больше наворачивать. Проект только в другую директорию пенесёшь и всё. VSCode как работал, так и будет работать.

**Comment by plutosshow** [comment]
openserver имеется, поднял, все работает.

**Comment by mprohorovevapps** [comment]
:thumbsup:
